logging:
  pattern:
    #console:"[Practical Java] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr{[%15.15t]}{faint} %clr{%-40.40c{1.}}{cyan} %clr{:}{faint} %m%n${sys:LOG_EXCEPTION_CONVERSION_WORD}"
    console: "%d %-5level %logger : %msg%n"
server:
  port: 8081
spring:
  main:
    banner-mode: OFF
